### ISSUE TITLE
Standardise the activity diagram for last output message

### ISSUE THREAD

**Issue by ZhiWei1010** [AY2324S2-CS2103-F09-2/tp#132]
Currently for the activity diagram we could standardise on how the last output message should be named

**Comment by SherisseTJW** [comment]
After discussion, we will proceed with the original method:
![image](https://github.com/AY2324S2-CS2103-F09-2/tp/assets/63995220/4a24f6c7-f172-4ac9-bda1-6b46598abcbd)

Assuming that when errors are thrown, it also means that an error message will be outputted to the user in the GUI.
