### ISSUE TITLE
[PE-D][Tester D] ID of deleted patient not coherent with the specified ID

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F09-2/tp#194]
![image.png](https://raw.githubusercontent.com/YowSiaoKang/ped/main/files/e9d3508e-9f4c-4a1e-8849-eefad331719f.png)

![image.png](https://raw.githubusercontent.com/YowSiaoKang/ped/main/files/4391309f-b220-421e-aacc-985a4d09a457.png)

When deleting a patient, the ID specified in the message is wrong.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: YowSiaoKang/ped#6

**Comment by SherisseTJW** [comment]
Discrepancy in Patient Hospital ID and the ID in PatientSync

**Comment by SherisseTJW** [comment]
Best option here seems to be to highlight in the UG about the difference as I foresee this being an issue that we may encounter in the final PE as well (since we alr have issues about the Hospital ID in PE-D)
