### ISSUE TITLE
[PE-D][Tester E] Full name is not show when length exceed horizontal length of the window.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F09-2/tp#200]
## Description

![Screenshot 2024-04-05 at 17.00.39.png](https://raw.githubusercontent.com/c-wenlong/ped/main/files/986e2c18-3255-46b2-91f7-845a61f6a256.png)

The system does not display the full name when it is too long.

## Fix 

There should be an upper limit on the length for name.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: c-wenlong/ped#8

**Comment by SherisseTJW** [comment]
![image](https://github.com/AY2324S2-CS2103-F09-2/tp/assets/63995220/414427b9-9154-49d8-8a3e-ba9404f5c9bc)


Since its an extreme input scenario, can put into planned enhancements.

(Might be good to lump together for all fields since this seems to be a recurring issue)

**Comment by NeoHW** [comment]
![Screenshot 2024-04-06 at 2 06 17 PM](https://github.com/AY2324S2-CS2103-F09-2/tp/assets/94470439/bc78954d-f7ca-4127-89e1-d56b47134ecf)
Not a bug, can ignore
