### ISSUE TITLE
[PE-D][Tester E] Editing field 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F09-2/tp#204]
## Description

![Screenshot 2024-04-05 at 17.07.09.png](https://raw.githubusercontent.com/c-wenlong/ped/main/files/2fcd4d5f-b12b-4312-a0ee-9ac5096e8679.png)

Editing a field that already exists does not throw an exception. (sorry guys, this is really minor though)

## Fix

Throw an exception when editing does not change the value of the field so that user are aware of it.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: c-wenlong/ped#9

**Comment by NeoHW** [comment]
im assuming this means that there is no warning or note that if the edited field is the same then nothing happens?  Instead of a field that is already existing there

~Editing a field that already exists~ Editing a field to something that is the same as the previous input ?

**Comment by SherisseTJW** [comment]
Seems to be so, best course of action seems to be just adding a note to the UG that editing a field s.t. the new value is the original value is allowed but does not change anything? 

Either that, or can consider this invalid

**Comment by choowengyan** [comment]
Additional clarification will be done on UG & DG
