### ISSUE TITLE
[PE-D][Tester B] Unsure what the person ID is for

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F09-2/tp#208]
As the ID is unable to be accessed anywhere after creation, it could be removed altogether. Alternatively, would it be better to use NRIC instead of a integer ID? 

![image.png](https://raw.githubusercontent.com/AwJoey/ped/main/files/5dde94a9-e938-4344-ae58-5e5122d4af16.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: AwJoey/ped#4

**Comment by SherisseTJW** [comment]
Probably can just add a note in the UG that the Hospital ID is for duplicate checks?

**Comment by NeoHW** [comment]
![Screenshot 2024-04-06 at 1 53 42 PM](https://github.com/AY2324S2-CS2103-F09-2/tp/assets/94470439/ae42e3cc-6a08-4660-8fe9-0d748c189d7f)

**Comment by ZhiWei1010** [comment]
NRIC is confidential and sensitive information and the nurse should not hold on to the NRIC of patients especially on personal apps like PatientSync, I'm pretty sure it breaches PDPA.

**Comment by SherisseTJW** [comment]
Put in planned enhancement as well (low priority)

**Comment by choowengyan** [comment]
Will put a note under UG & DG to clarify this.
