### ISSUE TITLE
[PE-D][Tester A] Inaccurate Date check

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F09-2/tp#233]
As shown, 30th of Feburary should not be possible on the calendar.

![image.png](https://raw.githubusercontent.com/AL-ZT/ped/main/files/086a2dc2-36ba-4b37-b8d3-99e4cbf70a05.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: AL-ZT/ped#11

**Comment by SherisseTJW** [comment]
Planned Enhancement since no check for this existed beforehand so unable to fix it now
