### ISSUE TITLE
[PE-D][Tester B] Delete tag edge case not included in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F09-2/tp#235]
This edge case is not included in the UG which shows that if there are multiple tags removed and some are not found, the removal will still occur for those tags present.
![image.png](https://raw.githubusercontent.com/AwJoey/ped/main/files/6657d97f-7c82-4b94-be1a-92cd9f9a8e87.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: AwJoey/ped#7

**Comment by NeoHW** [comment]
![Screenshot 2024-04-06 at 1 25 33 PM](https://github.com/AY2324S2-CS2103-F09-2/tp/assets/94470439/dd7212fa-dbda-4faa-8be0-b8bdb2de8b9c)

Also already Specified in DG which is used for PE
