### ISSUE TITLE
Conversion from Person to Patient Model

### ISSUE THREAD

**Issue by SherisseTJW** [AY2324S2-CS2103-F09-2/tp#47]
In order to start working on all the other User Stories, we first need to add the Patient Model (editing the current existing Person Model). 

It is optimal to merge this in first, and quickly, rather than allow each person to implement their own and deal with severe conflicts later on, or to delay the implementation of the other user stories.

**Comment by NeoHW** [comment]
recommendation:
TODO: 
it might be easier to change pre-existing person model to fit current logic and TCs instead of doing a migration to new patient folder
